name: Fluel Tests
on: push
jobs:
  go-tests:
    name: Validate Infrastructure for Test1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16
      - uses: hashicorp/setup-terraform@v1.2.1
      - name: Download Go Modules
        working-directory: test
        run: go mod download
      - name: Run Go Tests
        working-directory: test
        run: go test -v 
        env:
          TF_VAR_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          TF_VAR_SECRET_KEY: ${{ secrets.SECRET_KEY }}
